services:
  - type: web
    name: portfolio-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Ranjith_Portfolio.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Ranjith_Portfolio.production_settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'yourdomain.com,localhost'
      - key: DATABASE_URL
        value: postgresql://portfolio_django_render_7e2a_user:20Z8kui1VxaBjKdUpUgLMJ09G6icpcvI@dpg-d1l196ndiees73f32un0-a.oregon-postgres.render.com/portfolio_django_render_7e2a
    autoDeploy: true
    plan: free
    staticPublishPath: staticfiles

databases:
  - name: portfolio-db
    plan: free
    postgresMajorVersion: 15 