services:
  - type: web
    name: ranjith-portfolio
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Ranjith_Portfolio.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ranjith-portfolio.onrender.com,ranjith-portfolio-db57.onrender.com
      - key: DATABASE_URL
        value: postgresql://portfolio_django_render_7e2a_user:20Z8kui1VxaBjKdUpUgLMJ09G6icpcvI@dpg-d1l196ndiees73f32un0-a.oregon-postgres.render.com/portfolio_django_render_7e2a
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: DEFAULT_FROM_EMAIL
        value: noreply@ranjith-portfolio.onrender.com
    healthCheckPath: /health/

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: starter 