services:
  - type: web
    name: ranjith-portfolio
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn Ranjith_Portfolio.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ranjith-portfolio.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: DEFAULT_FROM_EMAIL
        value: noreply@ranjith-portfolio.onrender.com
    healthCheckPath: /health/

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: starter 